### ISSUE TITLE
Adding "speed" parameter breaks animation

### ISSUE THREAD

**Issue by kurealnum** [zuramai/starback.js#11]
Adding the `speed` parameter to the Starback class init breaks the animation. The background still displays properly, but no stars are displayed. Take a look at [this](https://codepen.io/kurealnum/pen/MWzBLXK) Codepen for example.

**Comment by VladChernyak** [comment]
The documentation specifies the type of the expected parameter incorrectly.
You need to pass not a number, but an array with several values, for example:
```
{
  ...
  speed: [0.2, 0.4],
}
```
